"""
Report Agent: Formats and combines results from other agents into clean Markdown reports.

Used as the final step in the agent pipeline to produce user-facing output.
"""

import logging

logger = logging.getLogger(__name__)


class ReportAgent:
    """Formats agent results into structured Markdown reports."""

    def format_answer(self, answer: str, sources: str = "") -> str:
        """
        Format a Q&A answer with its sources.

        Args:
            answer: The answer text from an agent.
            sources: Formatted source citations.

        Returns:
            Markdown-formatted answer with sources section.
        """
        if not answer:
            return "*No answer generated.*"

        # If answer already has sources embedded, just ensure clean formatting
        if "**Sources**" in answer or "## Sources" in answer:
            return answer

        # Build clean markdown
        parts = [answer]
        if sources:
            parts.append("\n\n---\n### 📚 Sources\n" + sources)

        return "".join(parts)

    def format_search_results(self, papers: list[dict]) -> str:
        """
        Format Arxiv search results into a clean list.

        Args:
            papers: List of paper dicts from ArxivSearchAgent.

        Returns:
            Markdown-formatted search results.
        """
        if not papers:
            return "*No papers found.*"

        if "error" in papers[0]:
            return f"⚠️ {papers[0]['error']}"

        lines = ["## 🔍 Arxiv Search Results\n"]
        for i, paper in enumerate(papers, 1):
            lines.append(f"### {i}. {paper.get('title', 'Untitled')}")
            lines.append(f"**Authors**: {paper.get('authors', 'N/A')}")
            lines.append(f"**Published**: {paper.get('published', 'N/A')}")
            lines.append(f"**Link**: [{paper.get('arxiv_id', '')}]({paper.get('url', '#')})")
            # Show abstract as summary (fast, no LLM)
            summary = paper.get("summary") or paper.get("abstract", "")
            if summary:
                lines.append(f"\n*{summary}*")
            lines.append("")  # blank line separator

        return "\n".join(lines)

    def format_report(
        self,
        user_query: str,
        rag_answer: str,
        search_results: list[dict] = None,
        additional_notes: str = "",
    ) -> str:
        """
        Generate a comprehensive report combining RAG answer and optional search results.

        Args:
            user_query: The original user question.
            rag_answer: Answer from PaperAgent (RAG).
            search_results: Optional list of Arxiv search results.
            additional_notes: Any extra notes or context.

        Returns:
            Complete Markdown report.
        """
        sections = [
            "# 📋 Research Report\n",
            f"**Query**: {user_query}\n",
            "---",
            "## 💡 Analysis",
            rag_answer if rag_answer else "*No analysis available.*",
        ]

        if search_results:
            sections.append("\n---\n## 🔗 Related Papers from Arxiv\n")
            for i, paper in enumerate(search_results[:3], 1):
                if "error" in paper:
                    continue
                summary = paper.get("summary") or paper.get("abstract", "")
                sections.append(f"{i}. **{paper.get('title', '')}** — {summary}")

        if additional_notes:
            sections.append(f"\n---\n## 📝 Notes\n{additional_notes}")

        sections.append("\n---\n*Report generated by Research Agent*")

        return "\n\n".join(sections)
